=== carolcaomin/baoku_upload/autotest.web.framework.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://glodon.com"
	xmlns:glodon="http://glodon.com"
	elementFormDefault="qualified">
	<xs:element name="autotest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="engine" type="glodon:engineType">
					<xs:annotation>
						<xs:documentation>
							<![CDATA[浏览器引擎配置]]>
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="includePage" type="glodon:includePageType"
					minOccurs="0" maxOccurs="unbounded" >
				</xs:element>
				<xs:element name="pages">
					<xs:annotation>
						<xs:documentation><![CDATA[页面列表配置]]></xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="page" type="glodon:pageType" maxOccurs="unbounded" />
						</xs:sequence>
						<xs:attribute name="pagePackage" type="xs:string">
							<xs:annotation>
								<xs:documentation>
									<![CDATA[公用的Page类包]]>
								</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="dataSources" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation><![CDATA[数据源列表配置]]></xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dataSource" type="glodon:dataSourceType" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation><![CDATA[数据源配置]]></xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="engineType">
		<xs:attribute name="driver" type="glodon:engineTypeDriverEnum" default="chrome">
			<xs:annotation>
				<xs:documentation><![CDATA[浏览器类型配置，默认值为chrome，必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="remote" type="xs:anyURI" use="optional">
			<xs:annotation>
				<xs:documentation><![CDATA[远程服务模式，可选；例如http://192.168.1.2:4444/wd/hub。不填写的话即为本地模式]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeout" type="xs:positiveInteger">
			<xs:annotation>
				<xs:documentation><![CDATA[显示地设置元素查找超时事件，单位为秒，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="fullScreen" type="xs:boolean">
			<xs:annotation>
				<xs:documentation><![CDATA[浏览器全屏，可能会不支持，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="maximize" type="xs:boolean">
			<xs:annotation>
				<xs:documentation><![CDATA[如果为true的话，浏览器启动后会最大化，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="width" type="xs:positiveInteger">
			<xs:annotation>
				<xs:documentation><![CDATA[浏览器宽度，必须为正整数，单位为像素，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="height" type="xs:positiveInteger">
			<xs:annotation>
				<xs:documentation><![CDATA[浏览器高度，必须为正整数，单位为像素，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="includePageType">
		<xs:attribute name="pageConfig" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="engineTypeDriverEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ie" />
			<xs:enumeration value="chrome" />
			<xs:enumeration value="firefox" /> 
			<xs:enumeration value="opera" />
			<xs:enumeration value="safari" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="pageType" mixed="true">
		<xs:sequence>
			<xs:element name="field" type="glodon:pageFieldType" maxOccurs="unbounded" minOccurs="1">
				<xs:annotation>
					<xs:documentation><![CDATA[当前Page配置所对应的属性，必填。]]></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Page配置的唯一标示，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="class" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Page配置所对应的class（全路径），必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="url" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Page配置所对应的url地址，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="dataSource" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Page配置所对应的数据源名称，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="paramPrefix" type="xs:string" default="param">
			<xs:annotation>
				<xs:documentation><![CDATA[配置用于变量替换的参数前缀，默认值为param。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="pageFieldType" mixed="true">
		<xs:sequence>
			<xs:element name="locators" type="glodon:pageFieldLocators" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation><![CDATA[用于区域定位策略时配置定位方法。]]></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field配置所对应的名称，必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attributeGroup ref="glodon:pageFieldLocatorAttrGroup"></xs:attributeGroup>
		<xs:attribute name="data" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的简单数据源值，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="glodon:fieldTypeEnum" default="input">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的类型，默认值为input。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="action" type="xs:string" />
		<xs:attribute name="strategy" type="glodon:strategyEnum" default="priority">
			<xs:annotation>
				<xs:documentation><![CDATA[配置用于查找当前Field对应的元素的策略，默认值为priority。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="paramPrefix" type="xs:string" default="param">
			<xs:annotation>
				<xs:documentation><![CDATA[配置用于变量替换的参数前缀，默认值为param。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeout" type="xs:integer" default="0">
			<xs:annotation>
				<xs:documentation><![CDATA[显示地设置元素查找超时事件，单位为秒，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:attributeGroup name="pageFieldLocatorAttrGroup">
		<xs:attribute name="byId" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的元素的ID，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byCss" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的元素的css样式（class值），可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byName" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的元素的名称，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byXpath" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的元素的xpath，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byLinkText" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的a标签的文本，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byPartialLinkText" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的a标签的部分文本，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="byTagName" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[当前Field对应的标签名，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	
	<xs:complexType name="pageFieldLocators">
		<xs:sequence>
			<xs:element name="locator" type="glodon:pageFieldLocator" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation><![CDATA[区域定位策略定位方法。]]></xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="pageFieldLocator">
		<xs:attribute name="name" type="glodon:pageFieldLocatorTypeEnum" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[定位方法。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[定位方法对应的值。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeout" type="xs:long">
			<xs:annotation>
				<xs:documentation><![CDATA[显示地设置元素查找超时事件，单位为秒，可选。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="extend" type="xs:string">
			<xs:annotation>
				<xs:documentation><![CDATA[扩展属性。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="pageFieldLocatorTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="byId"></xs:enumeration>
			<xs:enumeration value="byCss"></xs:enumeration>
			<xs:enumeration value="byName"></xs:enumeration>
			<xs:enumeration value="byXpath"></xs:enumeration>
			<xs:enumeration value="byLinkText"></xs:enumeration>
			<xs:enumeration value="byPartialLinkText"></xs:enumeration>
			<xs:enumeration value="byTagName"></xs:enumeration>
			<xs:enumeration value="byIFrame"></xs:enumeration>
			<xs:enumeration value="byIFrameIndex"></xs:enumeration>
			<xs:enumeration value="byText"></xs:enumeration>
			<xs:enumeration value="byXAttr"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="strategyEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="priority"></xs:enumeration>
			<xs:enumeration value="cyle"></xs:enumeration>
			<xs:enumeration value="zone"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="fieldTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="input" />
			<xs:enumeration value="button" />
			<xs:enumeration value="select" />
			<xs:enumeration value="file_upload" />
			<xs:enumeration value="check_box_group" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="dataSourceType">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[数据源名称，必须是在数据源列表中唯一，必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="glodon:dataSourceTypeEnum" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[数据源类型，必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="resource" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation><![CDATA[资源位置，必填。]]></xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="dataSourceTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="xml_data_source">
				<xs:annotation>
					<xs:documentation><![CDATA[XML格式的数据源]]></xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="excel_data_source" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	<!-- 首页登操作-->
	<pages pagePackage="page">
		<page class="FirstPage" url="${param.url}">
			<!-- 首页登陆点击 -->
			<field name="firstButton" byXpath="//span[text()='首页']" type="button"/>
			<!-- 手机号 -->
			<field name="telNum" byXpath="//input[@placeholder='手机号']" type="input"/>
			<!-- 验证码 -->
			<field name="VerificationCode" byXpath="//input[@placeholder='验证码']" type="input"/>
			<!-- 登录按钮 -->
			<field name="loginBtn" byXpath="//div[@id='app']/div[3]/div/div[4]" type="button"/>
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anxinComprehens.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	
	<!-- 安心综合医疗保险-->
	<pages pagePackage="page">
		<page class="AnxinComprehPage">
			<!-- 立即投保 -->
			<field name="insureCBtn" byXpath="//div[@id='app']/div[3]/div/div[3]/div[2]/div/div[1]/button" type="button"/>
			<!-- 以上全无 -->
			<field name="allNotCBtn" byXpath="//span[text()='以上全无']" type="button"/>
			
			<field name="nameCHolder" byXpath="//input[@placeholder='请输入投保人的姓名']" type="input"/>
			<field name="idCHolder" byXpath="//input[@placeholder='请输入投保人的身份证号']" type="input"/>
			<field name="telCHolder" byXpath="//input[@placeholder='请输入投保人的手机号']" type="input"/>
			<field name="emailCHolder" byXpath="//input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			<field name="shebaoCBtn" byXpath="//div[@id='app']/div[3]/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			<field name="gouxuanCBtn" byXpath="//div[@id='app']/div[3]/div/span/i" type="button"/>
					
			<!-- 立即投保 -->
			<field name="lijiCBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anlianTravel.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	<!-- 首页登操作-->
	<pages pagePackage="page">
		<page class="AnlianTravelPage" dataSource="anliantest">
			<!-- 安联旅意险登录图片 -->
			<field name="loginPicture" byXpath="//div[@id='app']/div[3]/div/div[3]/div[3]/div[2]/a/img" type="button"/>
			<!-- 惠游版 -->
			<!-- 立即投保 -->
			<field name="insuredBtn" byXpath="//div[@id='app']/div[3]/div/div/div[3]/div[2]/div/div/div[1]/button" type="button"/>
			<!-- 畅游版 -->                     
			<field name="changTravelBtn" byXpath="//li[text()='畅游版']" type="button"/>
			<!-- 嗨游版 -->
			<field name="haiBtn" byXpath="//li[text()='嗨游版']" type="button"/>
			
			<!-- 投保信息页 -->
			<!-- 起保日期 -->
			<field name="beginDate" byXpath="//a[@data-confirm-text='确定']/div[2]" type="button"/>
			<!-- ok -->
			<field name="okBtn" byXpath="//div[text()='ok']" type="button"/>
						
			<!-- 投保人姓名 -->
			<field name="nameHolder" byXpath="//input[@placeholder='请输入投保人的姓名']" type="input"/>
			<!-- 身份证号 -->
			<field name="idHolder" byXpath="//input[@placeholder='请输入投保人的身份证号']" type="input"/>
			<!-- 手机号 -->
			<field name="telHolder" byXpath="//input[@placeholder='请输入投保人的手机号']" type="input"/>
			<!-- 电子保单邮件 -->
			<field name="emailHolder" byXpath="//input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			<!-- 被保人信息  本人 -->
			<field name="myselfBtn" byXpath="//div[@id='app']/div[3]/div/div/div[3]/div/div/div[2]/div/div[3]/div/div/div[1]" type="button"/>
			<!-- 勾选协议 -->
			<field name="check" byXpath="//div[@id='app']/div[3]/div/div/span/i" type="button"/>
			<!-- 立即投保 -->
			<field name="sureBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anxinHospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	
	<!-- 安心住院综合医疗保险-->
	<pages pagePackage="page">
		<page class="AnxinHospitalPage">
			<!-- 立即投保 -->
			<field name="insureHBtn" byXpath="//div[@id='app']/div[3]/div/div[3]/div[2]/div/div[1]/button" type="button"/>
			<!-- 以上全无 -->
			<field name="allNotBtn" byXpath="//span[text()='以上全无']" type="button"/>
			
			<!-- 请输入被保人的身高 -->
			<field name="height" byXpath="//input[@placeholder='请输入被保人的身高']" type="input"/>
			<!-- 请输入被保人的体重-->
			<field name="weight" byXpath="//input[@placeholder='请输入被保人的体重']" type="input"/>
			<!-- 下一步 -->
			<field name="nextBtn" byXpath="//div[@id='app']/div[3]/div/div[7]/button" type="button"/>
			
			<field name="nameHolder" byXpath="//input[@placeholder='请输入投保人的姓名']" type="input"/>
			<field name="idHolder" byXpath="//input[@placeholder='请输入投保人的身份证号']" type="input"/>
			<field name="telHolder" byXpath="//input[@placeholder='请输入投保人的手机号']" type="input"/>
			<field name="emailHolder" byXpath="//input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			<field name="shebaoBtn" byXpath="//div[@id='app']/div[3]/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			<field name="gouxuanBtn" byXpath="//div[@id='app']/div[3]/div/span/i" type="button"/>
					
			<!-- 立即投保 -->
			<field name="lijiBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anxinAllFamily.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	
	<!-- 全家保综合意外险-->
	<pages pagePackage="page">
		<page class="AnxinAllFamilyPage">
			<!-- 立即投保 -->
			<field name="insureAFBtn" byXpath="//div[@id='app']/div[3]/div/div[2]/div[2]/div/div[1]/button" type="button"/>
			
			<field name="nameMainHolder" byXpath="//input[@placeholder='请输入主被保人的姓名']" type="input"/>
			<field name="idMainHolder" byXpath="//input[@placeholder='请输入主被保人的身份证号']" type="input"/>
			<field name="telMainHolder" byXpath="//input[@placeholder='用于接受电子保单短信']" type="input"/>
			<field name="emailMainHolder" byXpath="//input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			<!-- 附被保人信息 -->
			<field name="relationshipHolder" byXpath="//div[@id='app']/div[3]/div/div[2]/div/div/div[2]/div[1]/div[3]/div/div/div[1]" type="button"/>
			<field name="nameAttachHolder" byXpath="//input[@placeholder='请输入附被保人的姓名']" type="input"/>
			<field name="idAttachHolder" byXpath="//input[@placeholder='请输入附被保人的身份证号']" type="input"/>
			
			<field name="gouxuanAFBtn" byXpath="//div[@id='app']/div[3]/div/span/i" type="button"/>
			<!-- 立即投保 -->
			<field name="lijiAFBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anxinHosCost.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	
	<!-- 安心住院费用医疗保险-->
	<pages pagePackage="page">
		<page class="AnxinHosCostPage">
			<!-- 立即投保 -->
			<field name="insureHCBtn" byXpath="//div[@id='app']/div[3]/div/div[3]/div[2]/div/div[1]/button" type="button"/>
			<!-- 以上全无 -->
			<field name="allNotHCBtn" byXpath="//span[text()='以上全无']" type="button"/>
			
			<field name="nameHCHolder" byXpath="//input[@placeholder='请输入投保人的姓名']" type="input"/>
			<field name="idHCHolder" byXpath="//input[@placeholder='请输入投保人的身份证号']" type="input"/>
			<field name="telHCHolder" byXpath="//input[@placeholder='请输入投保人的手机号']" type="input"/>
			<field name="emailHCHolder" byXpath="//input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			<field name="shebaoHCBtn" byXpath="//div[@id='app']/div[3]/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			<field name="gouxuanHCBtn" byXpath="//div[@id='app']/div[3]/div/span/i" type="button"/>
					
			<!-- 立即投保 -->
			<field name="lijiHCBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
		</page>
	</pages>
</autotest>

=== carolcaomin/baoku_upload/src/main/resources/findelement/common/anxinEFamily.xml
<?xml version="1.0" encoding="UTF-8"?>
<autotest xmlns="http://glodon.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://glodon.com ../../autotest.web.framework.xsd ">
	<engine driver="firefox" timeout="30" fullScreen="false" maximize="true" />
	
	<!-- 安心e家 元素定位-->
	<pages pagePackage="page">
		<page class="AnxinEFamilyPage">
			<!-- 立即投保 -->
			<field name="insureBtn" byXpath="//div[@id='app']/div[3]/div/div[3]/div[2]/div/div[1]/button" type="button"/>
			<!-- 以上全无 -->
			<field name="allNotBtn" byXpath="//span[text()='以上全无']" type="button"/>
			
			<!-- 投保人信息 -->
			<!-- 请输入你本人的姓名 -->
			<field name="nameSelf" byXpath="//div[@id='app']/div[3]/div/div[1]/div/div/div[2]/div[2]/input[@placeholder='请输入投保人的姓名']" type="input"/>
			<!-- 请输入你本人的身份证号 -->
			<field name="idSelf" byXpath="//div[@id='app']/div[3]/div/div[1]/div/div/div[3]/div[2]/input[@placeholder='请输入投保人的身份证号']" type="input"/>
			<!-- 请输入你本人的手机号 -->
			<field name="telSelf" byXpath="//div[@id='app']/div[3]/div/div[1]/div/div/div[4]/div[2]/input[@placeholder='请输入投保人的手机号']" type="input"/>
			<!-- 用于接收电子保单邮件 -->
			<field name="emailSelf" byXpath="//div[@id='app']/div[3]/div/div[1]/div/div/div[5]/div[2]/input[@placeholder='用于接收电子保单邮件']" type="input"/>
			
			
			<!-- 被保人1信息 -->
			<!-- 默认本人 -->
			<!--有社保  -->
			<field name="shebaoBtn" byXpath="//div[@id='app']/div[3]/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			
			<!-- 被保人2信息 -->
			<field name="shebaoBtnSecond" byXpath="//div[@id='app']/div[3]/div/div[3]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			<field name="nameSecond" byXpath="//div[@id='app']/div[3]/div/div[3]/div/div/div[4]/div[2]/input[@placeholder='请输入被保人的姓名']" type="input"/>
			<field name="idSecond"   byXpath="//div[@id='app']/div[3]/div/div[3]/div/div/div[5]/div[2]/input[@placeholder='请输入被保人的身份证号']" type="input"/>
											  
			<!-- 被保人3信息 -->
			<field name="shebaoBtnThird" byXpath="//div[@id='app']/div[3]/div/div[4]/div/div/div[3]/div/div[3]/div/div/div[1]" type="button"/>
			<field name="nameThird" byXpath="//div[@id='app']/div[3]/div/div[4]/div/div/div[4]/div[2]/input[@placeholder='请输入被保人的姓名']" type="input"/>
			<field name="idThird"   byXpath="//div[@id='app']/div[3]/div/div[4]/div/div/div[5]/div[2]/input[@placeholder='请输入被保人的身份证号']" type="input"/>
			
			<field name="gouxuan" byXpath="//div[@id='app']/div[3]/div/span/i" type="button"/>
			<!-- 立即投保 -->
			<field name="lijiBtn" byXpath="//div[text()='立即投保']" type="button"/>
			
		</page>
	</pages>
</autotest>
